- name: Install System Packages 1 (ninja-build gettext cmake unzip curl)

  become: true
  apt:
    name: ["ninja-build", "gettext", "cmake", "unzip", "curl"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (i3, tmux, flameshot, stow)

  become: true
  apt:
    name: ["i3", "tmux", "flameshot", "stow"]
  tags:
    - install
    - core
